<?php

namespace JP\MaritimeBundle\Repository;
use Doctrine\ORM\EntityRepository;
/**
 * FolderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FolderRepository extends EntityRepository
{


	public function getFolderByOwnerOrAffected($user)
			{
			  $qb = $this->createQueryBuilder('a')
			             ->leftJoin('a.affectation', 'c')
			             ->addSelect('c')
			            

			             ->Where('a.owner = :owner')
      					  	->setParameter('owner', $user)
      					 ->orWhere('c.user = :user')
      					  	->setParameter('user', $user);

			  return $qb->getQuery()
			            ->getResult();
			}

	
}
