finance_facture_index:
    path:     /
    defaults: { _controller: "JPFinanceBundle:Facture:index" }
    methods:  GET

finance_facture_show:
    path:     /{id}/show
    defaults: { _controller: "JPFinanceBundle:Facture:show" }
    methods:  GET

finance_facture_new:
    path:     /new
    defaults: { _controller: "JPFinanceBundle:Facture:new" }
    methods:  [GET, POST]

finance_facture_edit:
    path:     /{id}/edit
    defaults: { _controller: "JPFinanceBundle:Facture:edit" }
    methods:  [GET, POST]

finance_facture_delete:
    path:     /{id}/delete
    defaults: { _controller: "JPFinanceBundle:Facture:delete" }
    methods:  DELETE
