<?php

namespace JP\FinanceBundle\Repository;

/**
 * Facture_itemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Facture_itemRepository extends \Doctrine\ORM\EntityRepository
{
}
