<?php

namespace JP\MainBundle\Repository;
use Doctrine\ORM\EntityRepository ;
/**
 * DocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentRepository extends EntityRepository
{
	public function findByFolderAndStep($folder,$step)
		{
		  $qb = $this->createQueryBuilder('d');

		  $qb->where('d.folder = :folder')
		       ->setParameter('folder', $folder)
		     ->andWhere('d.step = :step')
       			->setParameter('step', $step)		     
		     ->orderBy('d.id', 'DESC')
		  ;

		  return $qb
		    ->getQuery()
		    ->getResult()
		  ;
		}


}
