folder_index:
    path:     /
    defaults: { _controller: "JPMaritimeBundle:Folder:index" }
    methods:  GET

folder_show:
    path:     /{id}/show
    defaults: { _controller: "JPMaritimeBundle:Folder:show" }
    methods:  GET

folder_new:
    path:     /new
    defaults: { _controller: "JPMaritimeBundle:Folder:new" }
    methods:  [GET, POST]

folder_edit:
    path:     /{id}/edit
    defaults: { _controller: "JPMaritimeBundle:Folder:edit" }
    methods:  [GET, POST]

folder_delete:
    path:     /{id}/delete
    defaults: { _controller: "JPMaritimeBundle:Folder:delete" }
    methods:  DELETE
